### ISSUE TITLE
How to get refresh token for more than 1 hour

### ISSUE THREAD

**Issue by thebatmanreturns** [TheNetworg/oauth2-azure#110]
Hi, how can I get the refresh token for more than 1 hour? 

```
try {
      $newToken = $oauthClient->getAccessToken('refresh_token', [
        'refresh_token' => $_SESSION["refreshToken"]
      ]);

      // Store the new values
      $this->updateTokens($newToken);

      return $newToken->getToken();
    }
    catch (League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) { 
      return '';
    }
```

**Comment by hajekj** [comment]
Refresh tokens are usually valid for 90 days, access tokens are valid for 1 hour unless set otherwise by tenant policy in Azure AD.

**Comment by thebatmanreturns** [comment]
Hi, I'm using the below code to get the refresh token, however, my session is getting expired after 1 hour. Don't know what's happening.

```
  $now = time() + 300;
  if ($_SESSION["tokenExpires"] <= $now) {
    // Token is expired (or very close to it)
    // so let's refresh

    // Initialize the OAuth client
   $oauthClient = new \League\OAuth2\Client\Provider\GenericProvider([
                'clientId'                => OAUTH_APP_ID,
                'clientSecret'            => OAUTH_APP_PASSWORD,
                'redirectUri'             => OAUTH_REDIRECT_URI,
                'urlAuthorize'            => OAUTH_AUTHORITY.OAUTH_AUTHORIZE_ENDPOINT,
                'urlAccessToken'          => OAUTH_AUTHORITY.OAUTH_TOKEN_ENDPOINT,
                'urlResourceOwnerDetails' => '',
                'scopes'                  => OAUTH_SCOPES
              ]);

    try {
      $newToken = $oauthClient->getAccessToken('refresh_token', [
        'refresh_token' => $_SESSION["refreshToken"]
      ]);

      // Store the new values
      $this->updateTokens($newToken);

      return $newToken->getToken();
    }
    catch (League\OAuth2\Client\Provider\Exception\IdentityProviderException $e) {
      return '';
    }
  }
```

**Comment by hajekj** [comment]
I don't think this has anything to do with the library. Rather PHP session's configuration, can you print your `phpinfo();` configuration and paste the value of `session.cookie_lifetime`?

**Comment by thebatmanreturns** [comment]
Hi,
session.gc_maxlifetime (Local Value -  1440 and Max Value - 1440)
session.cookie_lifetime (0 for Local and Max)

**Comment by hajekj** [comment]
`updateTokens` writes it into session? And when refreshing the refresh token contains data? Or it is empty? Do you get some error from AAD?

________________________________

**Comment by thebatmanreturns** [comment]
You're right! 
Here is my updateTokens function. I'm not getting any response from the application, If I reload the page, I'm getting logged out from the app.

```
  public function updateTokens($accessToken) {
   $_SESSION['accessToken'] = $accessToken->getToken();
      $_SESSION['refreshToken'] = $accessToken->getRefreshToken();
      $_SESSION['tokenExpires'] = $accessToken->getExpires();
}
```

**Comment by hajekj** [comment]
When you reload the page or close the browser? Because the definition of `session.cookie_lifetime` set to `0` means that the cookie will expire when you close the browser ([reference](session.cookie_lifetime)). Also your `session._gc_maxlifetime` set to 24 minutes could explain it as well ([reference](https://www.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime)) because the runtime will wipe the session data with each request (`gc_probability/gc_divisor`).

Are you logged out because the `$_SESSION` variable is empty? If so, it's probably the above and not related to AAD and token expiration.

**Comment by thebatmanreturns** [comment]
Yes, you're right! My $_SESSION variable is empty. What parameters and what threshold should I set for the PHP session? Can you please help me?

**Comment by hajekj** [comment]
I would suggest raising the `session.gc_maxlifetime` variable to higher like 24h and see if that helps, probably the `session.cookie_lifetime` to the same value as well eg. `86400` (24h * 60m * 60s).

**Comment by thebatmanreturns** [comment]
It Worked. Thanks, Mate.
