### ISSUE TITLE
Adding Proxy information

### ISSUE THREAD

**Issue by FrancisAugustine** [TheNetworg/oauth2-azure#128]
How to add proxy information like proxy host name and port in networg library?

**Comment by hajekj** [comment]
Hi, it should inherit configuration from [league/oauth2-client](https://github.com/thephpleague/oauth2-client/) package, so configuration should be the same as here: https://github.com/thephpleague/oauth2-client/blob/419d163a02654305773e07731dc26ce7528a574f/docs/usage.md#using-a-proxy
