### ISSUE TITLE
Support PHP8

### ISSUE THREAD

**Issue by Qrious** [TheNetworg/oauth2-azure#130]
Hi,

Currently this library can't be used together with PHP8. PHP8 has been officially released, so it would be nice to add PHP8 support. This would require `league/oauth2-client` 2.6 release, as that is their first php8 compatible release. 

Current error message:
```
Loading composer repositories with package information
 Updating dependencies
 Your requirements could not be resolved to an installable set of packages.
 
   Problem 1
     - Root composer.json requires thenetworg/oauth2-azure ^2.0 -> satisfiable by thenetworg/oauth2-azure[v2.0.0].
     - thenetworg/oauth2-azure v2.0.0 requires php ^5.6|^7.0 -> your php version (8.0.0) does not satisfy that requirement.
```

**Comment by hajekj** [comment]
Hey there, could you please test it with oauth2-client v2.6 and report back if anything is not working? I will be happy to bump the supported PHP version if everything works fine.

**Comment by Qrious** [comment]
I will test it, however i'd like to note that my use case of your plugin is limited, as I only use it for authentication.

After a quick glance of the source code I don't expect any issues with an upgrade, but i'll let you know the results of my tests 👍.

**Comment by Qrious** [comment]
I can confirm that my use-case works with oauth2-client v2.6 :), it should be safe to bump the supported PHP version.

**Comment by hajekj** [comment]
I have just added it to master, https://github.com/TheNetworg/oauth2-azure/commit/fc059d1c50b0301c745a430273f1492b192e1f15 currently available under `dev-master` via Composer (https://packagist.org/packages/thenetworg/oauth2-azure#dev-master). I will probably release it as `v2.0.1` once I finish checking on League's changelog, to make sure we didn't do anything breaking here.
