### ISSUE TITLE
Proposal: add "appid" query parameter

### ISSUE THREAD

**Issue by infabo** [TheNetworg/oauth2-azure#151]
If the application has custom signing keys you can add a `appid` parameter to the openid-configuration-URL, so you receive the correct `jwks_uri` with the additional keys.

see https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

![image](https://user-images.githubusercontent.com/3999104/144051135-42a98d17-41e1-4d8d-b56e-c08c73d2eae3.png)

https://github.com/TheNetworg/oauth2-azure/blob/3f8d322e9cb5b8713cc3cc785bbeef0165b921bf/src/Provider/Azure.php#L69

It may be safe to add the `appid`-queryparam in all cases.

**Comment by hajekj** [comment]
This is pretty neat, didn't know about this feature!
