### ISSUE TITLE
Difference with Microsoft official tutorial

### ISSUE THREAD

**Issue by JulioJu** [TheNetworg/oauth2-azure#153]
Hi,

Currently, the official example from Microsoft Microsoft advise to use https://github.com/thephpleague/oauth2-client barely. 

See also https://docs.microsoft.com/en-us/graph/tutorials/php?tutorial-step=3 (Laravel is not mandatory) .

What do you think about this official advise ?

Thanks in advance

**Comment by JulioJu** [comment]
It seams that there is some shortcut

**Comment by hajekj** [comment]
Hi, I think it depends what your use case is. If it is just plain authentication, you are all good with oauth2-client mentioned above. If you would like to do some advanced scenarios - like protecting an API, using on-behalf-of flow and calling APIs in an easier way, I believe this library is going to serve you much better.

**Comment by JulioJu** [comment]
Thanks for your answer @hajekj :-)
