### ISSUE TITLE
Improve security for the token flow and add Web API protection

### ISSUE THREAD

**Issue by hajekj** [TheNetworg/oauth2-azure#16]
As per @vibronet's comments during BUILD 2016, the following improvements will be made in order to comply with security [requirements on Azure AD/OpenID](https://azure.microsoft.com/en-us/documentation/articles/active-directory-v2-tokens/#validating-tokens).
This also requires different `AccessToken` class handling as described in https://github.com/thephpleague/oauth2-client/issues/513.

- [x] Always validate the `id_token` signature
    - When we obtain new `access_token`, `id_token` is provided as well. The signature should be always validated whenever constructing the `AccessToken` object instead of checking it when calling `$provider->getResourceOwner($token);`. If invalid, an exception should be returned.
    - At the moment, the resource owner is obtained from the `access_token` which is wrong due to the fact, that with the 2.0 Azure AD authentication endpoints, it is not guaranteed that the `access_token` is still going to be a JWT (as per @vibronet's advice during BUILD 2016).
- [x] Always validate following `id_token` claims
    - [x] Audience (`aud`) claim - to verify that the `id_token` was intended to be given to your app
    - [x] Not Before (`nbf`) and Expiration Time (`exp`) claims - to verify that the `id_token` has not expired
    - [x] Issuer (`iss`) claim - to verify that the token was indeed issued to your app
        - This also requires the ability to turn off the validation and use a custom one when multitenant (*/common/* endpoint) application scenario is used
        - In case of a single tenant application in use with v2.0 endpoint, it will also allow for easier tenant filtering.
- [x] Ability to protect your web API with this library - going to introduce a function like `validateAccessToken($token)` which is going to return either the parsed token which your app received or throw an exception with the error.
- [x] Add documentation and example of protecting your Web API with `validateAccessToken($token)`
- [x] Add support for `urn:ietf:params:oauth:grant-type:jwt-bearer` grant type (use `setGrant` to register it), also reflect it in the README.md
    - Will be added as `TheNetworg\OAuth2\Client\Grant\JwtBearer` for shorter name and referenced as `jwt_bearer` in `$provider->getAccessToken(...)`
- [x] Add method `$provider->getLogoutUrl($post_logout_redirect_uri)` to make logging out more streamlined.
    - [x] Implement
    - [x] Add documentation to README.md
- [x] Update `composer.json` to support version 1.4.0 and higher of [thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client)

**The full implementation is going to require quite a lot of testing, because this could potentially break plenty of things if implemented wrong, so it might take a while before it gets released.**

**Comment by Crecket** [comment]
`This also requires the ability to turn off the validation and use a custom one when multitenant (/common/ endpoint) application scenario is used`

Looks like this isn't the case and it is causing v2.0 usage to break for me with my implementation. 

It is throwing an invalid issuer error since `https://sts.windows.net/9188040d-6c67-4c5b-b112-36a304b66dad/` does not match `https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0` which I assume is caused by the usage of the common endpoints? I don't see a way to disable this check aswell

**Comment by hajekj** [comment]
I will have to check this and get back to you. So you are using regular AAD created app with v2.0 endpoints, right?

**Comment by Crecket** [comment]
Yeah so I basically use the options described in the readme

```
$provider->pathAuthorize = "/oauth2/v2.0/authorize";
$provider->pathToken = "/oauth2/v2.0/token";
$provider->scope = ["openid"];
```

**Comment by Crecket** [comment]
Ah I think I found it, there is an API call to `'https://login.windows.net/' . $tenant . '/.well-known/openid-configuration'` to get the issuer. But if I check my endpoints in my azure portal it shows 

`https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`

So that might be the reason why?

**Comment by Crecket** [comment]
Almost forgot, I also modified the `https://login.windows.net/common/discovery/keys` url to use the v2.0 keys since Firebase JWT was giving me an error for a missing KID value.
