### ISSUE TITLE
Automatic Refresh Token not working

### ISSUE THREAD

**Issue by Lampone** [TheNetworg/oauth2-azure#19]
In [Azure.php](https://github.com/TheNetworg/oauth2-azure/blob/master/src/Provider/Azure.php) at the request function a $app variable is referenced, but it is never declared.

`if ($accessToken->hasExpired()) {
            $accessToken = $app->OAuth2->provider->getAccessToken('refresh_token', [
                'refresh_token' => $app->OAuth2->token->getRefreshToken(),
                'resource' => $this->urlAPI
            ]);
        }`

I fixed it with a reference to $this and to $accessToken, since we are already in the provider class.

`if ($accessToken->hasExpired()) {
            $accessToken = $this->getAccessToken('refresh_token', [
                'refresh_token' => $accessToken->getRefreshToken(),
                 'resource' => $this->urlAPI
            ]);
        }`

Also for the Office365 API (outlook.office.com) you are not allowed to send a 'resource' field. Ist the Office365 API not in the Scope of this project or just not implemented yet?

**Comment by hajekj** [comment]
Hello, this is fixed in: https://github.com/TheNetworg/oauth2-azure/tree/dev_16 - I still have to run some scenarios, in order to push it as next release, I suggest you try that version (should be available through Composer as "dev_16").

I see the issue there. What would be a viable solution for you? Adding for example `$provider->authAsResource = bool;`?

**Comment by Lampone** [comment]
Oh i didnt see it was already fixed^^

For the `resource` problem: Your suggestion would probably fix it. But I also tried to implement the sync functionality (https://msdn.microsoft.com/office/office365/api/task-rest-operations#Synchronizetasksortaskfolders) and for that to work you cant filter the response `$response['value']` like it is currently. 

Wouldn't it be better to create new Classes for the different API's and extract the differences of the API that way. May be they could inherit from Azure Class?

Note of warning: I have just looked at outlook.office.com api, so I dont know much about the others or about the oAuth library in general. 

PS: Thx for the quick response, much appreciated.

**Comment by hajekj** [comment]
Are you using plain `$provider->get(..)` method for getting the contents?

Also currently working on [v2.0.0](https://github.com/TheNetworg/oauth2-azure/issues/21) which improves quite a lot of things and simplifies many processes (it might take a while to get it ready for shipping tho).

**Comment by Lampone** [comment]
Yes I am. 

Thx for the update

**Comment by hajekj** [comment]
Oh, that explains - you will be better off with using `$provider->getObjects` - it fetches all the data by following the links automatically. Additionally, you can take a look at [$provider->request](https://github.com/TheNetworg/oauth2-azure/blob/master/src/Provider/Azure.php#L164) method and create your own - it is currently implemented as private.
