### ISSUE TITLE
Unnecessary response manipulation

### ISSUE THREAD

**Issue by shadowhand** [TheNetworg/oauth2-azure#2]
This [double json encode/decode](https://github.com/TheNetworg/oauth2-azure/blob/c7fb53189930bd7f4d96427441ada1a4bcb3b19a/src/Provider/Azure.php#L94) is not necessary and breaks the return type hinting of the `AbstractProvider`, which says that responses return `array`, not `object`.

**Comment by hajekj** [comment]
This should now be fixed. Thank you for pointing this out.
