### ISSUE TITLE
Micorsoft Entra ID and msal-browser/2.37.1 error validation access token

### ISSUE THREAD

**Issue by Sampei4** [TheNetworg/oauth2-azure#202]
Hi, I get the following error when I try to validate the access token:

```
Firebase\JWT\SignatureInvalidException: Signature verification failed
vendor\thenetworg\oauth2-azure\src\Provider\Azure.php(277): Firebase\JWT\JWT::decode()
TheNetworg\OAuth2\Client\Provider\Azure->validateAccessToken()
```

**Comment by al-n** [comment]
I have the same issue - could you solve it or does anyone else know what the problem is?

**Comment by beriba** [comment]
I don't know if that's still relevant for you but I managed to get rid of this error by using idToken instead of accessToken. The internet says that may have some security implications but by reading the code from this repo, I think that's the only option to make it work
