### ISSUE TITLE
How to restore token object from access_code

### ISSUE THREAD

**Issue by vincentfierant** [TheNetworg/oauth2-azure#22]
Maybe I'm looking in the wrong direction, but how would one go about to restore the token object from an access_code in storage (say in a session). It looks like the public function validateAccessToken in Azure.php is the right candidate, but it throws an error

`Undefined variable: provider	
Fatal error: Call to a member function getClientId() on null in D:\home\site\vendor\thenetworg\oauth2-azure\src\Provider\Azure.php on line 237`

Am I missing something?

**Comment by hajekj** [comment]
What do you mean by access_code? Do you mean the code which is returned by the authorization code flow?
