### ISSUE TITLE
composer install fails on v2.0.0 branch

### ISSUE THREAD

**Issue by kanhaic** [TheNetworg/oauth2-azure#25]
Hi,

We have been using the v2.0.0 branch and noticed that the composer is failing because of missing  requirement

 ```
Problem 1
    - Installation request for thenetworg/oauth2-azure 2.0.0.x-dev -> satisfiable by thenetworg/oauth2-azure[v2.0.0.x-dev].
    - thenetworg/oauth2-azure v2.0.0.x-dev requires gree/jose ^2.1 -> no matching package found.
```

Can you take a look at it and see if you are using that library?

Kanhai

**Comment by hajekj** [comment]
Hello, it appears like it is some sort of left-over from my previous testing and it appears that the package has been transfered under different account (https://github.com/nov/jose-php).

I have removed the requirement from the 2.0.0 branch (https://github.com/TheNetworg/oauth2-azure/commit/9fb6268a00e175b77d056ddca2f19919eea0a697).

Packagist already picked up the latest commit so it should be safe to try again.

Please also note that v2.0.0 is still not finished and there are still a few things to work on, see https://github.com/TheNetworg/oauth2-azure/issues/21

Let me know if you encounter any other issues with this library.

**Comment by kanhaic** [comment]
Thank you buddy. V2 is working well for our requirements.

Regards,

Kanhai Chhugani
+91-98201 46196 | +1 408 915 5251
kanhai@chhugani.org | http://www.kchhugani.com
Twitter: http://twitter.com/kanhaic | Linkedin: http://in.linkedin.com/in/kanhaic

**Comment by lkm** [comment]
There's still a requirement for `JOSE_JWK` here https://github.com/TheNetworg/oauth2-azure/blob/v2.0.0/src/Provider/Azure.php#L344

Is there any suitable replacement library?

**Comment by hajekj** [comment]
Yes, working on a solution - going to use [phpseclib](https://packagist.org/packages/phpseclib/phpseclib) as a replacement and then:
```php
$rsa = new Crypt_RSA();
$rsa->setPublicKey('<RSAKeyValue>
    <Modulus>' . $n . '</Modulus>
    <Exponent>' . $e . '</Exponent>
    </RSAKeyValue>');
$public_key = $rsa->getPublicKey();
```
Going to push the update tonight to fix this and eliminate the issue in future releases.

**Comment by hajekj** [comment]
@lkm: This should be now finally fixed, thanks for letting me know.

**Comment by easyhrworld** [comment]
Hi,

Composer install is broken again with following message:
```
Problem 1
    - thenetworg/oauth2-azure v2.0.0.x-dev requires phpseclib ~2.0 -> no matching package found.
    - thenetworg/oauth2-azure v2.0.0.x-dev requires phpseclib ~2.0 -> no matching package found.
    - Installation request for thenetworg/oauth2-azure v2.0.0.x-dev -> satisfiable by thenetworg/oauth2-azure[v2.0.0.x-dev].
```
Looks like phpseclib is not using v2.0.0.x-dev version. Kindly look into it.

EasyHR Team

**Comment by hajekj** [comment]
There was an incorrect package name, accidentaly put `phpseclib` instead of `phpseclib/phpseclib`

**Comment by easyhrworld** [comment]
Thank you. It is fixed now.

EasyHR Team

**Comment by lkm** [comment]
Cheers @hajekj, very quick turnaround on that one. Thanks!
