### ISSUE TITLE
Composer install not keeping up with git

### ISSUE THREAD

**Issue by davenorthcreek** [TheNetworg/oauth2-azure#27]
When I replace the vendor/thenetworg/oauth2-azure/src folder with a git cloned folder, all the errors go away (and I get a logout function).  Things are not synced.  Is there something you can do from here?
-git newb

**Comment by hajekj** [comment]
What exactly are you trying to do? I am quite confused here.

**Comment by davenorthcreek** [comment]
When I use composer to integrate your solution into laravel, the code is out of date.  My solution was to clone your repository directly from here and symlink the src folder.  It seems the version composer has access to (labelled 1.1.1) is not up-to-date with this repository.

**Comment by hajekj** [comment]
You should be able to specify a version of the package in `composer.json` file as per https://packagist.org/packages/thenetworg/oauth2-azure.

**Comment by davenorthcreek** [comment]
It is specified as 1.1.1 (which is the latest release from github, right?) but the release version is missing at least the getLogoutUrl() function, which is mentioned in the readme.md.
If you do a 
# composer require thenetworg/oauth2-azure
then diff src/Azure.php with the same file on git, do you see differences?  
Given the last change was August, I am wondering how to get composer to see the latest (and working) version of the code.

**Comment by hajekj** [comment]
Could you post the diff (screenshot) or the changes to here? I am currently unable to test this.

**Comment by davenorthcreek** [comment]
https://gist.github.com/davenorthcreek/71467490a1b1dbe134f57f5d841a6201

**Comment by hajekj** [comment]
Oh right, well, master version isn't equivalent of v1.1.1. I placed most of my focus on getting v2.0.0 released due to a lot of new functionality and refactoring. I would suggest using `v2.0.0.x-dev` as the version in Composer until I can get v2.0.0 out fully. The docs for v2 can be found [here](https://github.com/TheNetworg/oauth2-azure/tree/v2.0.0)

**Comment by davenorthcreek** [comment]
That explains things.  I will stick with 1.1.1 (working) until 2.0.0 is released, unless I hit a bug.
