### ISSUE TITLE
OpenSSL unable to verify data: error:04091068:rsa routines:INT_RSA_VERIFY:bad signature

### ISSUE THREAD

**Issue by santifdezmunoz** [TheNetworg/oauth2-azure#29]
Hi,

When I try to use any Graph resource I get following error:

OpenSSL unable to verify data: error:04091068:rsa routines:INT_RSA_VERIFY:bad signature

the resource URL that I'm using is https://graph.microsoft.com/

I set the provider configuration as is explained in the documentation, but keeps failing.

Here is the code that I'm using: 
        
       $settings = [
            'clientId'                  => config('azure.azureKey'),
            'clientSecret'              => config('azure.azureSecret'),
            'redirectUri'               => config('azure.azureRedirectUri')
        ];

        //$provider = new OAuth2Provider($settings);
        $provider = new AzureProvider($settings);
        $provider->scope = 'calendars.read';
        $provider->urlAPI = "https://graph.microsoft.com/v1.6/";
        $provider->resource = "https://graph.microsoft.com/";

If I use https://graph.windows.net as the resource, the token is correctly validated.

Thanks in advance!

**Comment by hajekj** [comment]
Hello, I have just tested this and it seems to work correctly for me. One issue I can see is that Microsoft Graph doesn't offer v1.6 endpoint, you should be using v1.0, which version of the library are you using - `dev-master`, `v1.1.1` or `v2.0.0.x-dev`?

**Comment by santifdezmunoz** [comment]
Great to know!! I'll make the modifications on the endpoint version that you suggested, and wait for the next release. Meanwhile I'll check it with v2.0.0.x-dev version.

Thanks again!
