### ISSUE TITLE
Resource owner defaults are incompatible with usage

### ISSUE THREAD

**Issue by shadowhand** [TheNetworg/oauth2-azure#3]
The [`AzureResourceOwner` has a default array response](https://github.com/TheNetworg/oauth2-azure/blob/c7fb53189930bd7f4d96427441ada1a4bcb3b19a/src/Provider/AzureResourceOwner.php#L10) but [is used as an object](https://github.com/TheNetworg/oauth2-azure/blob/c7fb53189930bd7f4d96427441ada1a4bcb3b19a/src/Provider/AzureResourceOwner.php#L15).

**Comment by hajekj** [comment]
This should now be fixed as well. Thanks for pointing this out.
