### ISSUE TITLE
Oauth2-client deprecated warning on PHP 7.1

### ISSUE THREAD

**Issue by jonty-comp** [TheNetworg/oauth2-azure#30]
I've been checking comparability with PHP 7.1 for our web app, which runs in a set of Docker containers, and I've noticed that the RandomFactory functions in oauth2-client have been replaced by native random functions as of [version 2.0 ](https://github.com/thephpleague/oauth2-client/blob/master/CHANGELOG.md#200).  Would it be possible for you to bump the version in this library (and/or your own 2.0 branch) to version 2.0+ of oauth2-client, or are there BC breaks?

Obviously it's not an imminent priority, but future proofing is good!

**Comment by hajekj** [comment]
I will check if everything works and if all is okay, will bump the version by tomorrow.

**Comment by hajekj** [comment]
Okay, all seems to be working fine, releasing as `v1.3.0` should be available within few moments.
