### ISSUE TITLE
getResponse() no longer compatible with this provider

### ISSUE THREAD

**Issue by kojot1234** [TheNetworg/oauth2-azure#31]
getResponse() no longer returns a parsed response. It now returns an unparsed PSR-7 instance and provider no longer works as of version 1.3.

OAuth client 2.0.0 renamed getResponse() to getParsedResponse().
https://github.com/thephpleague/oauth2-client/blob/master/CHANGELOG.md#200

Since you updated lib requirements, it broke the provider because it's unable to parse the response.

Please update all instances of getResponse to getParsedResponse.

#32

**Comment by hajekj** [comment]
Thanks a lot, merged the PR yesterday!
