### ISSUE TITLE
Invalid audience?

### ISSUE THREAD

**Issue by domkirby** [TheNetworg/oauth2-azure#33]
So I'm trying to integrate oauth with my app and I'm having some issues. I have the app registered in the portal and have verified my app id and secret. I'm able to sign on to AAD but when I get sent to the callback I get ``Uncaught RuntimeException: The audience is invalid!``

The error is occurring in AccessToken.php on line 42

Here is the code for my callback page (the tokens and such are drawn from a config database, I've verified that the data is being presented appropriately).

https://gist.github.com/domkirby/960b64c85c0223d9a2cde25d4c7378ce

**Comment by domkirby** [comment]
I did just decode the token and print it out in the browser. The aud property seems to match my app id

**Comment by domkirby** [comment]
ok I think I sorted it out, was an issue with my db I think.

**Comment by hajekj** [comment]
Awesome, great to hear you solved it!
