### ISSUE TITLE
how to change/update password?

### ISSUE THREAD

**Issue by ekhlascyblance** [TheNetworg/oauth2-azure#37]
Hi
In php
In Edit user there is no field for update password.
how can i update password using graph api.

Thanks
ikhlas

**Comment by hajekj** [comment]
Hi, this is possible by calling either Microsoft Graph (prefered method) by updating the [PasswordProfile](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/passwordprofile) of the user or by calling [Azure Graph](https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/users-operations#ResetUserPassword).

**Comment by ekhlascyblance** [comment]
Hi 
I am php web developer.
i have setup azure graph api for add update azure user detail.
add update work great.
but when i update user with password 
it will give me error " Insufficient privileges to complete the operation ".
I give all the required permission.
is there any special permission for update password  of auzre user
because add with password works fine.
only issue occur in updating password.
Any help appreciated 

Thanks 
Ekhlas mullas
