### ISSUE TITLE
accesstoken can reuse ?

### ISSUE THREAD

**Issue by leetuanchinh** [TheNetworg/oauth2-azure#44]
I login 1 account and can get access_token . 
$accessToken = $token->getToken();
$refreshToken = $token->getRefreshToken();

I can get profile from $token object
$this->_provider->get("me", $token);

After i store 2 string (accessToken, refreshToken) in db
Now, i want to reuse access token to get profile. But not working, because accessToken is string, not \League\OAuth2\Client\Token\AccessToken.

Show error "Call to a member function hasExpired() on string"

So, plz help me get $token object from accessToken string ?

**Comment by hajekj** [comment]
You need to store `$token` variable in your case, it is the `AccessToken` object.

**Comment by leetuanchinh** [comment]
i think i will use refresh token to get new access token

->getAccessToken('refresh_token', [
            'refresh_token' => $token,
            'resource' => 'https://graph.windows.net',
        ]);

but, i don't know refresh token never expired ? If refresh token expired ---> i can't not get access token ? How to check refresh_token expired ?

**Comment by hajekj** [comment]
The AccessToken object is a wrapper around refresh_token, access_token and others. If you call the `request` and similar methods, they handle the token refresh for you: https://github.com/TheNetworg/oauth2-azure/blob/master/src/Provider/Azure.php#L166

**Comment by Benoit382** [comment]
My solution : 

You must store this informations 
$accessToken = $token->getToken();
$refreshToken = $token->getRefreshToken();
$expiresToken = $token->getExpires();

You could create the access token
$realAccessToken = new \League\OAuth2\Client\Token\AccessToken([
            'access_token'=>$accessToken,
            'refresh_token' => $refreshToken,
            'expires_in' => $expiresToken,
]);

$this->_provider->get("me", $realAccessToken);

**Comment by hajekj** [comment]
Well, the proper and much more easy usage is showcased in this sample - https://github.com/TheNetworg/DreamSpark-SSO/blob/master/includes/app.oauth2.php#L6

**Comment by hajekj** [comment]
I am closing this issue since it didn't get any further response. If you need further assistance, please re-open it or create a new issue.
