### ISSUE TITLE
Uncaught exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'Unauthorized' 

### ISSUE THREAD

**Issue by jcrumpOS** [TheNetworg/oauth2-azure#45]
I'm getting this error trying to connect to a Microsoft Dynamics API, originally tried the Microsoft provider, but that was the giving the same message and was pointed in this direction for Azure provider, but get the same message :

Fatal error: Uncaught exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'Unauthorized' in C:\xampp\htdocs\apps\vendor\thenetworg\oauth2-azure\src\Provider\Azure.php:68 Stack trace: #0 C:\xampp\htdocs\apps\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(613): TheNetworg\OAuth2\Client\Provider\Azure->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 C:\xampp\htdocs\apps\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(528): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #2 C:\xampp\htdocs\apps\vendor\thenetworg\oauth2-azure\src\Provider\Azure.php(54): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken('authorization_c...', Array) #3 C:\xampp\htdocs\apps\test_dynamics_api.php(98): TheNetworg\OAuth2\Client\Provider\Azure->getAccessToken('authorization_c...', Array) #4 {main} thrown in C:\xampp\htdocs\apps\vendor\thenetworg\oauth2-azure\src\Provider\Azure.php on line 68

Any suggestions?
I'm getting a code back, but this error happens when it tries to get a token..

            // Try to get an access token (using the authorization code grant)
            $token = $provider->getAccessToken('authorization_code'...................

**Comment by Piotr21** [comment]
Hello,
I have this same a similar error? did you find a solution?
