### ISSUE TITLE
Error: Azure Class not found

### ISSUE THREAD

**Issue by Ryuuzan** [TheNetworg/oauth2-azure#49]
Hi! I'm new with azure ad so I'm not really well-versed with this subject.

I have done the install by using composer
-composer require league/oauth2-client
-composer require thenetworg/oauth2-azure

When i run the Authorization code flow i get the error:
 Fatal error: Class 'TheNetworg\oauth2\src\Provider\Azure' not found in C:\wamp\www\Auth_Azure\vendor\try.php on line 3

I only rewrote the parts which concern my connection.

Did i do something bad? Did i miss something? If you have an idea please?

**Comment by hajekj** [comment]
I would need to see more code to be able to troubleshoot but I would try making sure that you are including the Composer's autoload.php correctly:
```php
require __DIR__ . '/vendor/autoload.php';
```
If it doesn't help, can you post a part of your code?

**Comment by Ryuuzan** [comment]
Thanks it worked but i don't understand what it did.

**Comment by hajekj** [comment]
This has rather something to do with writing PHP and using Composer. I suggest you take a look at the getting started with Composer to understand more. https://getcomposer.org/doc/01-basic-usage.md
