### ISSUE TITLE
Call to undefined function getAccessTokenFromYourDataStore()

### ISSUE THREAD

**Issue by Ryuuzan** [TheNetworg/oauth2-azure#50]
Hi! Yeah another question already. Igot everything to work and after identification i go back on another page where i'm trying to get back the token to get user information but when i use this code i get the error Call to undefined function getAccessTokenFromYourDataStore().
I think i need to add an import but i'm not sure about it. Any ideas please?
Here is the code i'm using on my second page.
```php
<?php
//require_once('AccessToken.php');
require __DIR__ . '/vendor/autoload.php';
$provider = new TheNetworg\OAuth2\Client\Provider\Azure([
    'clientId'          => '',
    'clientSecret'      => '',
    'redirectUri'       => 'http://localhost/Co_Azure/index.php',
    'resource' => 'https://management.azure.com/'
]);


$existingAccessToken = getAccessTokenFromYourDataStore();

if ($existingAccessToken->hasExpired()) {
    $newAccessToken = $provider->getAccessToken('refresh_token', [
        'refresh_token' => $existingAccessToken->getRefreshToken()
    ]);

    // Purge old access token and store new access token to your data store.
}
$resourceOwner = $provider->getResourceOwner($existingAccessToken);
echo 'Hello, '.$resourceOwner->getFirstName().'!';
?>
```

**Comment by hajekj** [comment]
Please take a look at this sample application: https://github.com/TheNetworg/DreamSpark-SSO/blob/master/includes/app.oauth2.php#L7
That function is up to you to implement in order to store the user's information. It is dependant on the type of framework you choose to use. If you are not using any framework, you might as well store it directly in $_SESSION like it is shown in the link I posted above.

**Comment by Ryuuzan** [comment]
Sorry that's my last question (I hope), when i run your code I get the error
Call to a member function flash() on null
Does i need to include something?

**Comment by hajekj** [comment]
If you are running the DreamSpark application, it makes use of flash messages from Slim Framework, so you might need to install that through Composer first.

**Comment by Ryuuzan** [comment]
Oh ok thanks for the info

**Comment by Ryuuzan** [comment]
I installed the framework with composer slim/slim but i get the same error than before.
I tried to download only slim/flash but nothing. 
I also used composer slim/slim-skeleton but nothing else.

**Comment by hajekj** [comment]
Just run `composer install`

**Comment by Ryuuzan** [comment]
I already did it, but nothing

**Comment by inpresif** [comment]
> Hi! Yeah another question already. Igot everything to work and after identification i go back on another page where i'm trying to get back the token to get user information but when i use this code i get the error Call to undefined function getAccessTokenFromYourDataStore().
> I think i need to add an import but i'm not sure about it. Any ideas please?
> Here is the code i'm using on my second page.
> 
> ```
> <?php
> //require_once('AccessToken.php');
> require __DIR__ . '/vendor/autoload.php';
> $provider = new TheNetworg\OAuth2\Client\Provider\Azure([
>     'clientId'          => '',
>     'clientSecret'      => '',
>     'redirectUri'       => 'http://localhost/Co_Azure/index.php',
>     'resource' => 'https://management.azure.com/'
> ]);
> 
> 
> $existingAccessToken = getAccessTokenFromYourDataStore();
> 
> if ($existingAccessToken->hasExpired()) {
>     $newAccessToken = $provider->getAccessToken('refresh_token', [
>         'refresh_token' => $existingAccessToken->getRefreshToken()
>     ]);
> 
>     // Purge old access token and store new access token to your data store.
> }
> $resourceOwner = $provider->getResourceOwner($existingAccessToken);
> echo 'Hello, '.$resourceOwner->getFirstName().'!';
> ?>
> ```

Did you actually get a way to use getAccessTokenFromYourDataStore? I'm still kinda puzzled and there's not a lot to find about the function.
