### ISSUE TITLE
Fatal error with branch v2.0.0

### ISSUE THREAD

**Issue by davidpede** [TheNetworg/oauth2-azure#55]
Hi There,

I'm trying to use branch v2.0.0 but have an issue with the following error:

`Fatal error: Uncaught Error: Cannot use object of type GuzzleHttp\Psr7\Response as array in /var/www/html/foo/bar/vendors/thenetworg/oauth2-azure/src/Provider/Azure.php:51`

My code is:

```
$provider = new TheNetworg\OAuth2\Client\Provider\Azure([
  'clientId' => 'x',
  'clientSecret' => 'x',
  'redirectUri' => 'https://domain.com/',
  'metadata' => 'https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration',
  'responseType' => 'id_token',
  'responseMode' => 'form_post',
]);
$authUrl = $provider->getAuthorizationUrl();
```
Am I using it correctly - any advice on how to resolve?

Thanks

**Comment by davidpede** [comment]
I've tried with older versions of guzzle and oauth2-client but no luck.

It seems the `getOpenIdConfiguration()` function is returning the response object instead of an array here: https://github.com/TheNetworg/oauth2-azure/blob/v2.0.0/src/Provider/Azure.php#L328

Changing to: `return json_decode($response->getBody(),true);` fixes for me.

Do you want a pr or am I missing something? Seems odd that this hasn't come up before

**Comment by davidpede** [comment]
No problem - see pr #56.

Had a few other issues getting the v2.0.0 branch to work so see the pr for other fixes outside of this issue.

**Comment by hajekj** [comment]
Awesome! It has been merged, so I am closing the issue now.
