### ISSUE TITLE
MFA Support

### ISSUE THREAD

**Issue by default89** [TheNetworg/oauth2-azure#59]
My company had setup MFA location/device based.
When we are outside office with an unknown device, Azure requires MFA to be accessed.
The code you provided as example for logins exits in the Incorrect state condition right after login, not going through required device authentication (as example with Code or a Call).
You're library support this situation? Do you have some sample code of how to redirect to device authorization page or can you point me to some documentation?
Thanks

**Comment by hajekj** [comment]
Hi, MFA is supported by this library. It depends how you enforce the MFA - do you use conditional access in Azure AD? Or do you want to enforce it on application basis?

**Comment by default89** [comment]
We are actually using conditional access.

**Comment by hajekj** [comment]
Then it all should work since conditional access enforces it on Azure AD level.

**Comment by rothkj1022** [comment]
@default89 Were you able to get this working?  I am in the exact same situation and my users outside the office get 500 errors after entering their password.

**Comment by jdfreedman213** [comment]
@default89 @rothkj1022 @hajekj 

I’m running into this exact same issue. Did anyone ever figure out how to make it work?

**Comment by hajekj** [comment]
What does the 500 error say?

**Comment by jdfreedman** [comment]
I got it working by adding offline_access to the scope. Thanks.
