### ISSUE TITLE
Unable to issue tokens

### ISSUE THREAD

**Issue by mehulvadodariya2012** [TheNetworg/oauth2-azure#62]
**Sign in**

Sorry, but we’re having trouble signing you in.

AADSTS50020: We are unable to issue tokens from this API version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.

https://prnt.sc/l18lqa

**Comment by hajekj** [comment]
Hi, what sort of APIs are you trying to call?

**Comment by mehulvadodariya2012** [comment]
@hajekj  not understand your question

**Comment by hajekj** [comment]
What are you trying to do?

**Comment by mehulvadodariya2012** [comment]
I am trying to Login with Azure 
I have created app here https://apps.dev.microsoft.com using App ID and Secret. 
When app redirects for the code it gives this error. But I fixed this by changing API version.

Now I am getting issue after arriving on callback URL  https://prnt.sc/l19p70

**Comment by hajekj** [comment]
Could you by any chance include the code?

**Comment by mehulvadodariya2012** [comment]
I just changed 2 lines of code in thenetworg/oauth2-azure/src/Provider/Azure.php because of https://prnt.sc/l18lqa error 

   ```
 public $pathAuthorize = "/oauth2/authorize";
    public $pathToken = "/oauth2/token";
```
to
    ```
public $pathAuthorize = "/oauth2/v2.0/authorize";
    public $pathToken = "/oauth2/v2.0/token";
```

**Comment by hajekj** [comment]
Do you just need the user to authentication or call some API? I would suggest setting `$urlAPI` to an empty string if you need just authentication. Also, please note that you should not make changes in the library directly `thenetworg/oauth2-azure/src/Provider/Azure.php` and use configuration instead like shown in the documentation.

**Comment by mehulvadodariya2012** [comment]
Ok.
Thanks for your quick support. I appreciate it
