### ISSUE TITLE
Graph API Calls fail

### ISSUE THREAD

**Issue by boredom2** [TheNetworg/oauth2-azure#64]
With the latest Version 1.4.0, all Calls to /me via graph.windows.net fail with the Hint "a supported API Version must be provided".
I am not sure about the Purpose of the Changes of the \TheNetworg\OAuth2\Client\Provider\Azure in Lines  185ff, but these Changes are responsable for not appending the "?api-version=1.6" to the Graph API Calls anymore. When changing the "else" Branch to the old Version, everything works again.

Thanks,
Christoph

**Comment by davidpede** [comment]
This looks related to #67
