### ISSUE TITLE
Check for graph.windows.net sounds bogus

### ISSUE THREAD

**Issue by mcetkovsky** [TheNetworg/oauth2-azure#65]
Azure.php:186 contains the following check:

    if (strpos($this->urlAPI, "graph.windows.net") === TRUE)

As of [PHP Docs](http://php.net/strpos), the `strpos` returns either `FALSE` or `unsigned int`. It never specifically returns `TRUE`.

Instead, I would expect the condition to be

    if (strpos($this->urlAPI, "graph.windows.net") !== FALSE)

but I am not sure yet what the code is supposed to do.

It is also strange that if the condition would evaluate to true, the `$url` is always `null` so the condition  `strrpos($url, "?") === false` on line 193 always passes. As such, the complete `url` that the branch generates is `?api-version=1.6` (it completely ignores and missed the `tenant` and `ref` parts which is strange).

**Comment by hajekj** [comment]
Yes you are absolutely right, could you please make a pull request to fix this?

**Comment by mcetkovsky** [comment]
I can for the condition. But I am not sure what is the supposed way to build the `$url`.

**Comment by hajekj** [comment]
I will check on that and get back to you.

**Comment by mcetkovsky** [comment]
My guess that the following line is missing in the branch:

    $url = $this->urlAPI.$ref;

**Comment by hajekj** [comment]
I have merged the PR. I will be releasing it as 1.4.1 shortly. Thanks for the PR!

**Comment by jonty-comp** [comment]
Hi, could you release the v1.4.1 update?  We've just updated from 1.3 in our dev and it's stopped working due to this bug!

**Comment by hajekj** [comment]
Hi, I have just released 1.4.1.
