### ISSUE TITLE
Common tenant is not valid for graph API

### ISSUE THREAD

**Issue by mcetkovsky** [TheNetworg/oauth2-azure#68]
Calling

    $me = $provider->get("me", $token);

on graph API which effectively calls

    https://graph.windows.net/common/me?api-version=1.6

sometimes* fails reporting

    Invalid domain name in the request url

error.

If I understood the `Tenant identifier {tenant_id}` chapter in [docs](https://msdn.microsoft.com/en-us/library/azure/ad/graph/howto/azure-ad-graph-api-operations-overview) correctly, `myOrganization` should be used instead of `common`. Even better, as a special case, the tenant part makes no sense for `me` queries so the tenant part should be skipped, i. e. the query should call just `https://graph.windows.net/me?api-version=1.6`.

\* In my experience, the call usually proceeds for initial tokens obtained via `authorization_code` but it fails for tokens obtained via `refresh_token`.

**Comment by hajekj** [comment]
Well personally I would prefer addressing the Graph directly rather than using the short method which is rather legacy - in v2 I don’t plan on keeping the shortcut functionality for calling the API.

But in general you are right it should be replaced with ‘myorganization’.

**Comment by mcetkovsky** [comment]
I am not sure what you mean by the `addressing the Graph directly`. I am inheriting from the official `Authorization Code Flow` sample code in the repository's readme.

**Comment by hajekj** [comment]
Instead of typing me, use the full address - https://graph.windows.net/myorganization/...?api-version=1.6

**Comment by mcetkovsky** [comment]
Ok, I did that. Please, update accordingly the official sample in readme. Thanks.

**Comment by GermanPearls** [comment]
I'm experiencing the error
`invalid domain name in the request url`
when attempting to use with Graph API as well.

However, when I attempt to use the entire url as $ref, the function adds 'common/' in front of the url and I'm getting an error:
`bad request`

Thoughts on how to avoid this?

**Comment by hajekj** [comment]
Could you please share parts of your code please?

**Comment by GermanPearls** [comment]
Here's my request:

```
$getms365EventsURL = 'https://graph.microsoft.com/v1.0/users/' . $userID . '/calendars/' . $calendarID . '/events';
            $getms365EventsURL .= '?$select=subject,start,end,location,bodyPreview';
            $getms365EventsURL .= '&$orderby=start/dateTime';
            $getms365EventsURL .= '&$filter=start/dateTime ge \'' . $startDateFilter .'\')';

            $response = $this->provider->get($getms365EventsURL, $this->accessToken, $headers = []);
```

And the error:

```
Fatal error: Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: Bad request. Please fix the request before retrying. in C:\xampp\vendor\thenetworg\oauth2-azure\src\Provider\Azure.php:315 
Stack trace: 
#0 C:\xampp\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(628): TheNetworg\OAuth2\Client\Provider\Azure->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) 
#1 C:\xampp\vendor\thenetworg\oauth2-azure\src\Provider\Azure.php(173): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) 
#2 C:\xampp\vendor\thenetworg\oauth2-azure\src\Provider\Azure.php(104): TheNetworg\OAuth2\Client\Provider\Azure->request('get', 'common/https://...', Object(TheNetworg\OAuth2\Client\Token\AccessToken), Array) 
#3 C:\xampp\htdocs\digidash\classes\ms365calendarevents_class.php(73): TheNetworg\OAuth2\Client\Provider\Azure->get('https://graph.m...', Object(TheNetworg\OAuth2\Client\Token\AccessToken), Array) 
#4 C:\xampp\htdocs\digidash\classes\ms365calendarevents_cla in C:\xampp\vendor\thenetworg\oauth2-azure\src\Provider\Azure.php on line 315
```

**Comment by hajekj** [comment]
It appears to be failing here: https://github.com/TheNetworg/oauth2-azure/blob/8b8a384571ff4d776a0d6b124de891edcadd4002/src/Provider/Azure.php#L310 which means that `if (isset($data['odata.error']) || isset($data['error'])) {` the response contains some sort of an error. I would suggest trying to execute the same request via Microsoft Graph and checking what it returns.

**Comment by GermanPearls** [comment]
Thank you for your reply @hajekj . It appears I had it backwards and needed the Microsoft Graph endpoint to access calendar events, not the Azure endpoint. I got all the bugs worked out in my code and it is working properly when directed to the proper url.

**Comment by hajekj** [comment]
Awesome! Glad to hear that! Thanks for letting me know. Feel free to to reach out if you have any questions / issues.
