### ISSUE TITLE
Can i use this libary to gain an Access token(Without redirect)?

### ISSUE THREAD

**Issue by RScanlan1990** [TheNetworg/oauth2-azure#73]
Hi,

I have an OAuth2 protected web-service on azure, that has a controller which returns Json.

I would like to hit that controller from separate PHP site without redirecting the User, so I can just display the Json response on the PHP site.

I have manged to obtain the access token and connect to the service, but I am redirected to the services home page.

Can I gain the access token without redirecting the user? And then use that token to hit a controller?

Here is my current code,

(Also due to using PHP 5.5[Which I cannot upgrade] I am using 1.4.0 version of the library)

If i need to set up an API on Azure separately to my web-service just slap me with a wet-fish and tell me :)

`       
require_once("vendor/autoload.php");

        $provider = new TheNetworg\OAuth2\Client\Provider\Azure([
            'clientId' => 'SECRET',
            'clientSecret' => 'SECRET',
            'redirectUri' => 'WEBSITE/.auth/login/aad/callback',
        ]);

        if (!isset($_GET['code'])) {
            // If we don't have an authorization code then get one
            $authUrl = $provider->getAuthorizationUrl();
            $_SESSION['oauth2state'] = $provider->getState();
            header('Location: ' . $authUrl);
            exit;
        } else {
         // Try to get an access token (using the authorization code grant)
            $token = $provider->getAccessToken('authorization_code', [
                'code' => $_GET['code']
            ]);

            $accesstoken = $provider->getAccessToken('refresh_token', [
                'refresh_token' => $token->getRefreshToken(),
                'resource' => 'https://management.core.windows.net/'
            ]);

            $bearertoken = "Bearer " . $accesstoken->getToken();

            $client = new GuzzleHttp\Client([
                'base_uri' => 'WEBSITE',
                'timeout' => 2.0,
            ]);
        }

        try {
            $result = $client->request('GET', "/PresentationToPolicy/CaseSummary/TestAPI", [
                'headers' => [
                    'User-Agent' => 'testing/1.0',
                    'Accept' => 'application/json',
                    'Authorization' => $bearertoken
                ]
            ]);
        } catch (RequestException $e) {
            Zend_Debug::dump($e);
        } `

**Comment by RScanlan1990** [comment]
After a bit more reading it seems I am trying to connect to Azure using the wrong pipe-line, back to the docs. If anyone has some tips please comment :)

**Comment by JanPetterMG** [comment]
Trying to do the same thing.

Is it possible to archive this by logging in / redirecting once, then having your server receive the token, witch periodically makes sure to request new tokens using the refresh token?

It's obviously not an permanent solution, but it should work for up to 90 days, right?
Personally I'm not able to use the `Application permissions` set, due to missing admin consent...
