### ISSUE TITLE
Resource owner

### ISSUE THREAD

**Issue by davidsteinsland** [TheNetworg/oauth2-azure#8]
Shouldn't the method be something like:

```
    public function getResourceOwnerDetailsUrl(AccessToken $token)
    {
        return "https://graph.windows.net/me?api-version=1.6";
    }
```

This would make if work by:

```php
$me = $provider->getResourceOwner($token);
```

**Comment by hajekj** [comment]
You are right, I haven't paid much attention to the ResourceOwner stuff yet.

**Comment by hajekj** [comment]
Going to be implemented as per https://github.com/thephpleague/oauth2-client/issues/488

**Comment by hajekj** [comment]
Should be now implemented and documented.
