### ISSUE TITLE
post_logout_redirect_uri should be optional

### ISSUE THREAD

**Issue by dh-oswald** [TheNetworg/oauth2-azure#95]
The parameter in the function getLogoutUrl() should be made optional, since Microsoft itself only suggests it and there are cases, in which a user can just close the window after logout and it is not desirable to redirect him. 

My use case is a site with automatic logon and no page visible logged off (except login). There is no need to redirect the user.

https://github.com/TheNetworg/oauth2-azure/blob/8b8a384571ff4d776a0d6b124de891edcadd4002/src/Provider/Azure.php#L195

**Comment by hajekj** [comment]
Hi, that makes sense. Could you please submit a pull request for this? Would be glad to merge it.
